version: '3.8'

services:
  # Service for Django application
  web:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.db
    depends_on:
      - rabbitmq
      - redis

  # Service for the RabbitMQ message broker
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"   # Port for Celery
      - "15672:15672"  # Port for the RabbitMQ web interface (useful for debugging)

  # Service for Redis (used by Celery to store task results)
  redis:
    image: redis:6.2-alpine

  # Service for the Celery background task processor
  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./.env.db
    depends_on:
      - rabbitmq
      - redis