version: '3.8'

services:
  # --- MONITORING SERVICES ---
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - default

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    networks:
      - default

  # --- APPLICATION SERVICES ---
  web:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env.db
    depends_on:
      - rabbitmq
      - redis
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    networks:
      - default

  redis:
    image: redis:6.2-alpine
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    networks:
      - default

  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./.env.db
    depends_on:
      - rabbitmq
      - redis
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    networks:
      - default

volumes:
  grafana-data:
